"""Emit C test vectors for the DeepSeek V4.1 CPU reference primitives.

Values come from ds41_kernels_cpu (validated against the reference model's own semantics in
kernel.py), so the C side is checked against the same maths the oracle runs.
"""
import os, sys, numpy as np, torch
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ds41_kernels_cpu as K

torch.manual_seed(7)
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "test_dsv41_ref_vectors.inc")
buf = ["/* Generated by tests/deepseek_v41/gen_ref_vectors.py -- do not edit. */", ""]

def emit(name, arr):
    a = np.asarray(arr, dtype=np.float32).ravel()
    buf.append(f"static const float {name}[{a.size}] = {{")
    for i in range(0, a.size, 8):
        buf.append("    " + ", ".join(f"{v:.9g}f" for v in a[i:i+8]) + ",")
    buf.append("};")

def emit_i32(name, arr):
    a = np.asarray(arr, dtype=np.int32).ravel()
    buf.append(f"static const int32_t {name}[{a.size}] = {{")
    for i in range(0, a.size, 12):
        buf.append("    " + ", ".join(str(int(v)) for v in a[i:i+12]) + ",")
    buf.append("};")

# ---- 1. mHC split + Sinkhorn -------------------------------------------------
HC, N, ITERS, EPS = 4, 5, 20, 1e-6
MIX = (2 + HC) * HC
mixes = torch.randn(1, N, MIX)
hc_scale = torch.tensor([0.7, 1.3, 0.9])
hc_base = torch.randn(MIX) * 0.5
pre, post, comb = K.hc_split_sinkhorn(mixes, hc_scale, hc_base, HC, ITERS, EPS)
buf += [f"#define V_HC {HC}", f"#define V_HC_N {N}", f"#define V_HC_ITERS {ITERS}",
        f"#define V_HC_EPS {EPS:.9g}f", ""]
emit("v_hc_mixes", mixes); emit("v_hc_scale", hc_scale); emit("v_hc_base", hc_base)
emit("v_hc_pre", pre); emit("v_hc_post", post); emit("v_hc_comb", comb)

# ---- 2. sqrtsoftplus + noaux_tc routing --------------------------------------
NE, TOPK, ROUTE_SCALE = 8, 2, 1.5
logits = torch.randn(N, NE)
bias = torch.randn(NE) * 0.3
scores = torch.nn.functional.softplus(logits.float()).sqrt()
sel = (scores + bias).topk(TOPK, dim=-1)[1]
w = scores.gather(1, sel)
w = w / (w.sum(-1, keepdim=True) + 1e-20)
w = w * ROUTE_SCALE
buf += ["", f"#define V_NE {NE}", f"#define V_TOPK {TOPK}",
        f"#define V_ROUTE_SCALE {ROUTE_SCALE:.9g}f", ""]
emit("v_gate_logits", logits); emit("v_gate_bias", bias)
emit_i32("v_gate_idx", sel); emit("v_gate_w", w)

# ---- 3. sparse attention with sink -------------------------------------------
B, S, H, D, NKV, TK = 1, 3, 4, 8, 10, 6
q = torch.randn(B, S, H, D); kv = torch.randn(B, NKV, D)
sink = torch.randn(H) * 0.5
idxs = torch.full((B, S, TK), -1, dtype=torch.int32)
for s in range(S):                       # a causal-ish mix, plus -1 padding on the first row
    n = min(NKV, 2 + 3 * s)
    pick = torch.randperm(n)[:min(TK, n)].sort().values
    idxs[0, s, :pick.numel()] = pick.to(torch.int32)
scale = D ** -0.5
o = K.sparse_attn(q, kv, sink, idxs, scale)
buf += ["", f"#define V_S {S}", f"#define V_H {H}", f"#define V_D {D}",
        f"#define V_NKV {NKV}", f"#define V_TK {TK}", f"#define V_SCALE {scale:.9g}f", ""]
emit("v_attn_q", q); emit("v_attn_kv", kv); emit("v_attn_sink", sink)
emit_i32("v_attn_idxs", idxs); emit("v_attn_out", o)

# ---- 4. compressor ratio-r softmax pooling ----------------------------------
RATIO, CD, NG = 2, 8, 4
ckv = torch.randn(NG, RATIO, CD); cscore = torch.randn(NG, RATIO, CD)
pooled = (ckv.float() * cscore.float().softmax(dim=1)).sum(dim=1)
buf += ["", f"#define V_RATIO {RATIO}", f"#define V_CD {CD}", f"#define V_NG {NG}", ""]
emit("v_comp_kv", ckv); emit("v_comp_score", cscore); emit("v_comp_out", pooled)

open(OUT, "w").write("\n".join(buf) + "\n")
print(f"wrote {os.path.normpath(OUT)}  ({len(buf)} lines)")
print(f"  sinkhorn: comb row sums {comb.sum(-1)[0,0].tolist()}")
print(f"  routing:  idx {sel[0].tolist()} w {[round(x,4) for x in w[0].tolist()]}")
print(f"  attn out[0,0,0,:3] {[round(x,5) for x in o[0,0,0,:3].tolist()]}")

# ---- 5. engram n-gram hash ---------------------------------------------------
# Compressed ids are supplied directly: the tokenizer-dependent compressed map is a converter
# concern that gets baked into the GGUF, so the hash maths is tested in isolation.
NG_MAX, NHEAD, NPOS = 4, 3, 6            # 3 n-gram sizes (2,3,4-gram) x 3 heads
PAD_ID = 2
primes = np.array([[16000057, 16000063, 16000067],
                   [16000069, 16000079, 16000097],
                   [16000103, 16000111, 16000121]], dtype=np.int64)   # [ngram][head]
mult = np.array([3, 1234567891, 987654323, 555555557], dtype=np.int64)  # odd, per lookback
offs = np.concatenate([[0], np.cumsum(primes.ravel())[:-1]]).reshape(NG_MAX-1, NHEAD)
ids = np.array([11, 4, 4, 97, 2, 61], dtype=np.int64)                  # compressed ids
dead = np.array([0, 0, 0, 1, 0, 0], dtype=np.int32)                    # position 3 is an image span

toks = np.zeros((NPOS, NG_MAX), dtype=np.int64)
for p in range(NPOS):
    blocked = False
    for s in range(NG_MAX):
        if p - s < 0 or dead[p - s]: blocked = True
        toks[p, s] = PAD_ID if blocked else ids[p - s]
prod = toks * mult[None, :]
roll = prod[:, 0].copy(); cols = []
for i in range(1, NG_MAX):
    roll = np.bitwise_xor(roll, prod[:, i])
    cols.append((roll[:, None] % primes[i - 1][None, :]) + offs[i - 1][None, :])
hashes = np.concatenate(cols, axis=-1)   # [NPOS, (NG_MAX-1)*NHEAD]

buf += ["", f"#define V_NG_MAX {NG_MAX}", f"#define V_NHEAD {NHEAD}", f"#define V_NPOS {NPOS}",
        f"#define V_PAD_ID {PAD_ID}", ""]
emit_i32("v_eng_ids", ids); emit_i32("v_eng_dead", dead)
buf.append(f"static const int64_t v_eng_mult[{NG_MAX}] = {{ " + ", ".join(f"{int(v)}LL" for v in mult) + " };")
buf.append(f"static const int64_t v_eng_primes[{(NG_MAX-1)*NHEAD}] = {{ " + ", ".join(f"{int(v)}LL" for v in primes.ravel()) + " };")
buf.append(f"static const int64_t v_eng_offs[{(NG_MAX-1)*NHEAD}] = {{ " + ", ".join(f"{int(v)}LL" for v in offs.ravel()) + " };")
buf.append(f"static const int64_t v_eng_hash[{hashes.size}] = {{")
for i in range(0, hashes.size, 6):
    buf.append("    " + ", ".join(f"{int(v)}LL" for v in hashes.ravel()[i:i+6]) + ",")
buf.append("};")

# ---- 6. engram gate ---------------------------------------------------------
EDIM, EHC = 16, 4
xe = torch.randn(NPOS, EHC, EDIM)
key = torch.randn(NPOS, EHC, EDIM)
val = torch.randn(NPOS, EDIM)
qw = torch.randn(EHC, EDIM) * 0.5 + 1.0
kw = torch.randn(EHC, EDIM) * 0.5 + 1.0
EPS_E = 1e-20
wprod = qw.float() * kw.float()
h = xe.float()
rstd = torch.rsqrt(h.square().mean(-1) + EPS_E) * torch.rsqrt(key.square().mean(-1) + EPS_E)
dot = (h * wprod * key).sum(-1) * rstd * EDIM ** -0.5
gate = torch.sigmoid(torch.copysign(dot.abs().clamp_min(1e-6).sqrt(), dot))
out_e = h + gate.unsqueeze(-1) * val.float().unsqueeze(-2)
buf += ["", f"#define V_EDIM {EDIM}", f"#define V_EHC {EHC}", f"#define V_EPS_E {EPS_E:.9g}f", ""]
emit("v_eng_x", xe); emit("v_eng_key", key); emit("v_eng_val", val)
emit("v_eng_qw", qw); emit("v_eng_kw", kw); emit("v_eng_gate", gate); emit("v_eng_out", out_e)

# ---- 7. candidate block selection -------------------------------------------
CB_W, CB_BLK, CB_TOP = 14, 2, 3
clog = torch.randn(2, CB_W)
clog[0, 9:] = float("-inf")      # unreachable tail for query 0
clog[1, 12:] = float("-inf")
clens = torch.tensor([[9], [12]])
keep = K_keep = None
import torch.nn.functional as _F
pad = (-CB_W) % CB_BLK
sc = _F.pad(clog, (0, pad), value=float("-inf")).unflatten(-1, (-1, CB_BLK)).amax(-1)
nblk = sc.size(-1)
last = (clens - 1) // CB_BLK
sc = sc.masked_fill(torch.arange(nblk) == last, float("inf"))
top = sc.topk(min(CB_TOP, nblk), dim=-1)
keep = torch.zeros_like(sc, dtype=torch.bool).scatter_(-1, top.indices, top.values > float("-inf"))
keep = keep.repeat_interleave(CB_BLK, dim=-1)[..., :CB_W]
buf += ["", f"#define V_CB_W {CB_W}", f"#define V_CB_BLK {CB_BLK}", f"#define V_CB_TOP {CB_TOP}",
        f"#define V_CB_Q 2", ""]
emit("v_cb_logits", torch.where(torch.isinf(clog), torch.full_like(clog, -3.0e38), clog))
emit_i32("v_cb_lens", clens); emit_i32("v_cb_keep", keep.int())

open(OUT, "w").write("\n".join(buf) + "\n")
print(f"  engram hash[0] {hashes[0].tolist()}")
print(f"  engram gate[0] {[round(x,5) for x in gate[0].tolist()]}")
print(f"  candidate keep[0] {keep[0].int().tolist()}")
